# Generated by Django 3.0.3 on 2020-07-08 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requistion_total',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('date_made', models.DateField(db_column='date_made')),
                ('purpose', models.CharField(db_column='purpose', max_length=400)),
                ('total', models.FloatField(db_column='Total')),
            ],
            options={
                'verbose_name_plural': 'requistion_totals',
                'db_table': 'requistions_total',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='directorate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorate_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'directorates',
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200, verbose_name='employee name')),
                ('staff_id_num', models.CharField(max_length=20, unique=True, verbose_name='UNRAID No.')),
                ('date_left_org', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.CreateModel(
            name='period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=50, verbose_name='Period name')),
                ('p_number', models.IntegerField(verbose_name='period number')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('num_days', models.IntegerField(default=30, verbose_name='Number of Days')),
                ('p_flag', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'periods',
            },
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100, verbose_name='position')),
            ],
            options={
                'verbose_name_plural': 'positions',
            },
        ),
        migrations.CreateModel(
            name='ratetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='Rate Type')),
            ],
            options={
                'verbose_name_plural': 'ratetypes',
            },
        ),
        migrations.CreateModel(
            name='requesttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='Requistion Type')),
            ],
            options={
                'verbose_name_plural': 'requesttypes',
            },
        ),
        migrations.CreateModel(
            name='requistion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.TextField(verbose_name='Purpose')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requistions.employee')),
            ],
            options={
                'verbose_name_plural': 'requistion',
            },
        ),
        migrations.CreateModel(
            name='requistiondetailtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'requistiondetailtypes',
            },
        ),
        migrations.CreateModel(
            name='salaryscale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_name', models.CharField(max_length=100, verbose_name='salary scale name')),
            ],
            options={
                'verbose_name_plural': 'salaryscales',
            },
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100, verbose_name='station')),
            ],
            options={
                'verbose_name_plural': 'stations',
            },
        ),
        migrations.CreateModel(
            name='requistiondetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndays', models.IntegerField(default=0, verbose_name='Number of days')),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('rate', models.FloatField(default=0.0, verbose_name='Allowances Rate')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('detail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requistions.requistiondetailtype')),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requistions.employee')),
                ('period_claimed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requistions.period')),
                ('requistionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requistions.requistion')),
            ],
            options={
                'verbose_name_plural': 'requistiondetails',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requistions.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requistions.salaryscale'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requistions.station'),
        ),
        migrations.CreateModel(
            name='allowancerate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('allowance_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requistions.ratetype')),
                ('allowance_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requistions.salaryscale')),
            ],
            options={
                'verbose_name_plural': 'allowancerates',
            },
        ),
    ]
