# Generated by Django 3.0.8 on 2020-07-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requistions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
