# Generated by Django 3.0.8 on 2020-07-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requistions', '0002_requisition_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisitiondetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='requisitiondetail',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Allowances Rate'),
        ),
    ]
